modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="smg_world"
version="1.0.0"
displayName="SMG World"
credits="Made by SMG"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="HyperGDD ~ Snaky"
description='''
A custom mod for Minecraft made by SMG
'''

[[dependencies.smg_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




